name: morning-digest

on:
  schedule:
    # GitHub Actions runs on UTC. Monday 06:00 Paris (CET/CEST) ≈ 04:00 UTC.
    - cron: "0 4 * * 1"
  workflow_dispatch:

env:
  TZ: Europe/Paris

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run digest
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          SMTP_SERVER: ${{ vars.SMTP_SERVER }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ vars.MAIL_FROM }}
          MAIL_TO: ${{ vars.MAIL_TO }}
        run: |
          python nothing.py --csv rss_list.csv --topn 10 --hours 168
